// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56uWFk-sZIKkYFbLOHFwEgi-lRnLr9vs',
    appId: '1:161724590082:web:8d86808fba451a73329f1b',
    messagingSenderId: '161724590082',
    projectId: 'prime-policy-manager-21fb6',
    authDomain: 'prime-policy-manager-21fb6.firebaseapp.com',
    storageBucket: 'prime-policy-manager-21fb6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBue9fbAl0Q9H8ghOjDmKTz5f4bw86_oxg',
    appId: '1:161724590082:android:67a92109fd6e7c20329f1b',
    messagingSenderId: '161724590082',
    projectId: 'prime-policy-manager-21fb6',
    storageBucket: 'prime-policy-manager-21fb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIl0Um_7LXWmFfVcJMEwq7SGht-88q-Tg',
    appId: '1:161724590082:ios:83e2d6216fa957a6329f1b',
    messagingSenderId: '161724590082',
    projectId: 'prime-policy-manager-21fb6',
    storageBucket: 'prime-policy-manager-21fb6.firebasestorage.app',
    iosBundleId: 'com.example.primePolicy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIl0Um_7LXWmFfVcJMEwq7SGht-88q-Tg',
    appId: '1:161724590082:ios:83e2d6216fa957a6329f1b',
    messagingSenderId: '161724590082',
    projectId: 'prime-policy-manager-21fb6',
    storageBucket: 'prime-policy-manager-21fb6.firebasestorage.app',
    iosBundleId: 'com.example.primePolicy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC56uWFk-sZIKkYFbLOHFwEgi-lRnLr9vs',
    appId: '1:161724590082:web:ce732f359be5c238329f1b',
    messagingSenderId: '161724590082',
    projectId: 'prime-policy-manager-21fb6',
    authDomain: 'prime-policy-manager-21fb6.firebaseapp.com',
    storageBucket: 'prime-policy-manager-21fb6.firebasestorage.app',
  );
}
